encoding: utf-8
port: 5678
host: 0.0.0.0

title: znfang's Blog
keywords: [znfang, 后端, 算法, 杭州]
description: '到底要做一个什么样的人？'

exclude: [webpack.config.js, package.json, Gemfile, Gemfile.lock, src, node_modules]
# plugins: [jekyll-paginate, jemoji]
plugins: [jekyll-paginate]

permalink: /:title.html
highlighter: rouge
markdown: kramdown
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
# emoji:
#     src: 'https://api.fooleap.org'
paginate: 10
repository: znfang/znfang.github.io

nickname: znfang
home: https://znfang.github.io
# api: https://api.fooleap.org
# IMG_PATH: //source.fooleap.org
IMG_PATH: /img
tongji: '86b12b861045f3b67b5b5bcdba02a4ad'
analytics: 'UA-139257940-1'

# Comments  disqus needs vpn
disqus_username: znfang
